### ISSUE TITLE
Network Warning

### ISSUE THREAD

**Issue by Wit3** [tighten/takeout#255]
From last week, every command in my laravel application ( artisan or composer ) generate 3 row Warning in console.

WARN[0000] network takeout: network.external.name is deprecated in favor of network.name
WARN[0000] network takeout: network.external.name is deprecated in favor of network.name
WARN[0000] network takeout: network.external.name is deprecated in favor of network.name

That's fault of any update of docker?

**Comment by Wit3** [comment]
Close the issue because the warning was printed by docker deprecated property when implementing takeout as network in laravel sail docker-composer.yml.

For anyone with this problem, rename in docker-compose.yml this

```
networks:
    sail:
        driver: bridge
    takeout:
        name: takeout
            name: takeout
```

to this

```
networks:
    sail:
        driver: bridge
    takeout:
        name: takeout

```
